"""added many-to-many assoc table for mealplans and recipes

Revision ID: 21259cd02807
Revises: 0e20d7601fcb
Create Date: 2018-11-27 14:59:39.259380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21259cd02807'
down_revision = '0e20d7601fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Meals Recipes',
    sa.Column('mealplan_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mealplan_id'], ['mealplan.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Meals Recipes')
    # ### end Alembic commands ###
